"""add custom template to config revisions

Revision ID: 650c3368386f
Revises: fed7683e826f
Create Date: 2026-09-09 09:48:13.894264

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = '650c3368386f'
down_revision = 'fed7683e826f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_api_config_revisions', sa.Column('custom_template_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_api_config_revisions', 'custom_template_json')
    # ### end Alembic commands ###
