"""init schema

Revision ID: fed7683e826f
Revises: 
Create Date: 2026-09-07 18:12:04.028755

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fed7683e826f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('resource_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('ip_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('safe_meta_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_event_created', 'audit_events', ['event_type', 'created_at'], unique=False)
    op.create_index('ix_audit_user_created', 'audit_events', ['user_id', 'created_at'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_index('ix_conversations_user_status_updated', 'conversations', ['user_id', 'status', 'updated_at', 'id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('video_api_configs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('current_revision', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_api_configs_user_id'), 'video_api_configs', ['user_id'], unique=False)
    op.create_index('uq_configs_user_display_name', 'video_api_configs', ['user_id', 'display_name'], unique=True, sqlite_where=sa.text("status != 'deleted'"))
    op.create_table('assets',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('original_name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('retention_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('size_bytes > 0', name='ck_assets_size_positive'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_assets_user_created', 'assets', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_assets_user_id'), 'assets', ['user_id'], unique=False)
    op.create_index('ix_assets_user_sha256', 'assets', ['user_id', 'sha256'], unique=False)
    op.create_table('conversation_contexts',
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary_through_message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary_model', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('summary_prompt_version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('messages',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=100000), nullable=False),
    sa.Column('structured_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reply_to_message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('client_request_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('request_fingerprint', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'client_request_id', name='uq_messages_conv_client_request')
    )
    op.create_index('ix_messages_conv_created', 'messages', ['conversation_id', 'created_at', 'id'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('video_api_config_revisions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('protocol_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('template_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('template_version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('remote_model_id', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('encrypted_auth_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('public_options_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('capability_profile_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('capabilities_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('capability_source', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('verification_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('key_hint_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relay_risk_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_error_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['video_api_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', 'revision', name='uq_config_revisions_config_revision')
    )
    op.create_index(op.f('ix_video_api_config_revisions_config_id'), 'video_api_config_revisions', ['config_id'], unique=False)
    op.create_table('video_projects',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_spec_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_spec_version', sa.Integer(), nullable=False),
    sa.Column('confirmed_spec_version', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('confirmed_spec_version IS NULL OR confirmed_spec_version <= current_spec_version', name='ck_projects_confirmed_le_current'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    op.create_index(op.f('ix_video_projects_user_id'), 'video_projects', ['user_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assistant_message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('base_spec_version', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('provider_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('tool_call_count', sa.Integer(), nullable=False),
    sa.Column('provider_request_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assistant_message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_message_id')
    )
    op.create_index(op.f('ix_agent_runs_conversation_id'), 'agent_runs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_user_id'), 'agent_runs', ['user_id'], unique=False)
    op.create_index('uq_agent_runs_one_active_per_conversation', 'agent_runs', ['conversation_id'], unique=True, sqlite_where=sa.text("status IN ('pending', 'running')"))
    op.create_table('video_project_versions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('spec_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('suggested_prompt', sqlmodel.sql.sqltypes.AutoString(length=20000), nullable=True),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('source_message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['video_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version', name='uq_project_versions_project_version')
    )
    op.create_index(op.f('ix_video_project_versions_project_id'), 'video_project_versions', ['project_id'], unique=False)
    op.create_table('tool_executions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('input_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_run_id', 'sequence', name='uq_tool_executions_run_sequence')
    )
    op.create_index(op.f('ix_tool_executions_agent_run_id'), 'tool_executions', ['agent_run_id'], unique=False)
    op.create_table('video_jobs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_version_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_version', sa.Integer(), nullable=False),
    sa.Column('api_config_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_config_revision_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('previous_job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('request_fingerprint', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('protocol_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('adapter_version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('template_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('template_version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('model_profile_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('model_profile_version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('remote_model_id', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('request_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_task_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('provider_context_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('encrypted_result_ref_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('download_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('download_attempts', sa.Integer(), nullable=False),
    sa.Column('local_asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('next_poll_at', sa.DateTime(), nullable=True),
    sa.Column('poll_count', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_config_id'], ['video_api_configs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['api_config_revision_id'], ['video_api_config_revisions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['local_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['previous_job_id'], ['video_jobs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['video_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_version_id'], ['video_project_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_video_jobs_user_idempotency')
    )
    op.create_index(op.f('ix_video_jobs_conversation_id'), 'video_jobs', ['conversation_id'], unique=False)
    op.create_index('ix_video_jobs_download_completed', 'video_jobs', ['download_status', 'completed_at'], unique=False)
    op.create_index(op.f('ix_video_jobs_project_id'), 'video_jobs', ['project_id'], unique=False)
    op.create_index('ix_video_jobs_status_nextpoll', 'video_jobs', ['status', 'next_poll_at'], unique=False)
    op.create_index('ix_video_jobs_user_created', 'video_jobs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_video_jobs_user_id'), 'video_jobs', ['user_id'], unique=False)
    op.create_index('uq_video_jobs_revision_providertask', 'video_jobs', ['api_config_revision_id', 'provider_task_id'], unique=True, sqlite_where=sa.text('provider_task_id IS NOT NULL'))
    op.create_table('message_citations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_execution_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('snippet', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_execution_id'], ['tool_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_citations_message_id'), 'message_citations', ['message_id'], unique=False)
    op.create_table('video_job_assets',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('video_job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['video_job_id'], ['video_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_job_id', 'role', 'position', name='uq_video_job_assets_role_position')
    )
    op.create_index(op.f('ix_video_job_assets_asset_id'), 'video_job_assets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_video_job_assets_video_job_id'), 'video_job_assets', ['video_job_id'], unique=False)
    op.create_table('video_job_events',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('video_job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('from_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('to_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('safe_payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_job_id'], ['video_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_job_events_video_job_id'), 'video_job_events', ['video_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_job_events_video_job_id'), table_name='video_job_events')
    op.drop_table('video_job_events')
    op.drop_index(op.f('ix_video_job_assets_video_job_id'), table_name='video_job_assets')
    op.drop_index(op.f('ix_video_job_assets_asset_id'), table_name='video_job_assets')
    op.drop_table('video_job_assets')
    op.drop_index(op.f('ix_message_citations_message_id'), table_name='message_citations')
    op.drop_table('message_citations')
    op.drop_index('uq_video_jobs_revision_providertask', table_name='video_jobs', sqlite_where=sa.text('provider_task_id IS NOT NULL'))
    op.drop_index(op.f('ix_video_jobs_user_id'), table_name='video_jobs')
    op.drop_index('ix_video_jobs_user_created', table_name='video_jobs')
    op.drop_index('ix_video_jobs_status_nextpoll', table_name='video_jobs')
    op.drop_index(op.f('ix_video_jobs_project_id'), table_name='video_jobs')
    op.drop_index('ix_video_jobs_download_completed', table_name='video_jobs')
    op.drop_index(op.f('ix_video_jobs_conversation_id'), table_name='video_jobs')
    op.drop_table('video_jobs')
    op.drop_index(op.f('ix_tool_executions_agent_run_id'), table_name='tool_executions')
    op.drop_table('tool_executions')
    op.drop_index(op.f('ix_video_project_versions_project_id'), table_name='video_project_versions')
    op.drop_table('video_project_versions')
    op.drop_index('uq_agent_runs_one_active_per_conversation', table_name='agent_runs', sqlite_where=sa.text("status IN ('pending', 'running')"))
    op.drop_index(op.f('ix_agent_runs_user_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_conversation_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_video_projects_user_id'), table_name='video_projects')
    op.drop_table('video_projects')
    op.drop_index(op.f('ix_video_api_config_revisions_config_id'), table_name='video_api_config_revisions')
    op.drop_table('video_api_config_revisions')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index('ix_messages_conv_created', table_name='messages')
    op.drop_table('messages')
    op.drop_table('conversation_contexts')
    op.drop_index('ix_assets_user_sha256', table_name='assets')
    op.drop_index(op.f('ix_assets_user_id'), table_name='assets')
    op.drop_index('ix_assets_user_created', table_name='assets')
    op.drop_table('assets')
    op.drop_index('uq_configs_user_display_name', table_name='video_api_configs', sqlite_where=sa.text("status != 'deleted'"))
    op.drop_index(op.f('ix_video_api_configs_user_id'), table_name='video_api_configs')
    op.drop_table('video_api_configs')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('ix_conversations_user_status_updated', table_name='conversations')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_audit_user_created', table_name='audit_events')
    op.drop_index('ix_audit_event_created', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
